---
- name: Create a Login-Admin user
  ansible.builtin.user:
    name: "{{ linux_user }}"
    password: "{{ linux_password }}"
    groups:
     - wheel
    state: present

- name: Adding new user to sudoers file so they can run sudo commands
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^{{ linux_user }}'
    line: '{{ linux_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'